== Overview

There are four main operations a client needs to do with
attachments for calendar data: add, update, remove, and
retrieve. The first three operations are carried out by the
client issuing an HTTP `POST` request on the calendar object
resource to which the attachment is associated and specifying
the appropriate "action" query parameter (see <<attachment-post-request>>).
In the case of the
remove operation, the client can alternatively directly update
the calendar object resource and remove the relevant "`ATTACH`"
properties (see <<attachment-remove-put>>). The
retrieve operation is accomplished by simply
issuing an HTTP `GET` request targeting the attachment URI
specified by the calendar resource's "`ATTACH`" property (see
<<attachment-retrieve>>).

iCalendar data stored in a CalDAV calendar object resource
can contain multiple components when recurrences are involved.
In such a situation, the client needs to be able to target a
specific recurrence instance or multiple instances when adding
or deleting attachments. As a result, the `POST` request needs to
provide a way for the client to specify which recurrence
instances should be targeted for the attachment operation.  This
is accomplished through use of additional query parameters on
the `POST` request-URI.

[[requirements]]
=== Requirements

A server that supports the features described in this
specification is `REQUIRED` to support the CalDAV
"calendar-access" <<RFC4791>> features.

In addition, such a server `SHOULD` support the
"return=representation" Prefer header
field <<RFC7240>> preference on successful HTTP `PUT` and `POST` requests
targeting existing calendar object resources, by returning the
new representation of that calendar resource (including its
new ETag header field value) in the response.

=== Discovering Support for Managed Attachments

A server supporting the features described in this
specification `MUST` include "calendar-managed-attachments" as a
token in the DAV response header field (as defined in
<<RFC4918, section=10.1>>) from an `OPTIONS` request on a
calendar home collection.

A server might choose to not support storing managed
attachments on a per-recurrence instance basis (i.e., they can
only be added to all instances as a whole). If that is the
case, the server `MUST` also include
"calendar-managed-attachments-no-recurrence" as a token in the
DAV response header field from an `OPTIONS` request on a calendar home
collection. When that field is present, clients `MUST NOT`
attempt any managed attachment operations that target specific
recurrence instances.

[[attachment-post-request]]
=== `POST` Request for Managing Attachments

An HTTP `POST` request is used to add, update, or remove
attachments.
These requests are subject to the preconditions listed in
<<errors>>.
The request-URI will contain various query
parameters to specify the behavior.

[[action]]
==== `action`= Query Parameter

The "`action`" query parameter is used to identify which
attachment operation the client is requesting. This
parameter `MUST` be present once on each `POST` request used to
manage attachments. One of these three values `MUST` be used:

`attachment-add`:: Indicates an operation that
is adding an attachment to a calendar object resource. See
<<attachment-add>> for more details.

`attachment-update`:: Indicates an operation
that is updating an existing attachment on a calendar
object resource. See <<attachment-update>>
for more details.

`attachment-remove`:: Indicates an operation
that is removing an attachment from a calendar object
resource. See <<attachment-remove>> for more
details.

Example:: https://calendar.example.com/events/1.ics?action=attachment-add

[[rid]]
==== `rid`= Query Parameter

The "`rid`" query parameter is used to identify which
recurrence instances are being targeted by the client for
the attachment operation. This query parameter `MUST` contain
one or more items, separated by commas (0x2C). The item
values can be in one of two forms:

Master instance:: The value "`M`"
(case-insensitive) refers to the "`master`" recurrence
instance, i.e., the component that does not include a
"`RECURRENCE-ID`" property. This item `MUST` be present only
once.

Specific instance:: A specific iCalendar
instance is targeted by using its "`RECURRENCE-ID`" value as
the item value. That value `MUST` correspond to the
`RECURRENCE-ID` value as stored in the calendar object
resource (i.e. without any conversion to UTC). If multiple
items of this form are used, they MUST be unique
values. For example, to target a recurrence defined by property
`RECURRENCE-ID;TZID=America/Montreal:20111022T160000`, the
query parameter `rid=20111022T160000` would be used.
+
If the "`rid`" query parameter is not present, all recurrence
instances in the calendar object resource are targeted.
+
The "`rid`" query parameter `MUST NOT` be present in the case
of an update operation, or if the server chooses not to
support per-recurrence instance managed attachments (see
<<requirements>>).

Example (targeting the master instance and a specific overridden instance):: https://calendar.example.com/events/1.ics?action=attachment-add&rid=M,20111022T160000

[[managed-id]]
==== `managed-id`= Query Parameter

The "`managed-id`" query parameter is used to identify
which "`ATTACH`" property is being updated or removed. The
value of this query parameter `MUST` match the
<<MANAGED-ID-parameter,MANAGED-ID>>
property parameter value on the "`ATTACH`" property in the
calendar object resource instance(s) targeted by the
request.

The "`managed-id`" query parameter `MUST NOT` be present in
the case of an add operation.

Example:: https://calendar.example.com/events/1.ics?action=attachment-update&managed-id=aUNhbGVuZGFy

[[attachment-add]]
=== Adding attachments

To add an attachment to an existing calendar object
resource, the following occurs:

. The client issues a `POST` request targeted at the calendar
object resource.

.. The request-URI will include an "`action`" query
parameter with the value "`attachment-add`" (see <<action>>).

.. If all recurrence instances are having an attachment
added, the "`rid`" query parameter is not present in the
request-URI. If one or more specific recurrence instances
are targeted, then the request-URI will include a "`rid`"
query parameter containing the list of instances (see
<<rid>>).

.. The body of the request contains the data for the
attachment.

.. The client `MUST` include a valid Content-Type
header field describing the media type of the attachment (as
required by `HTTP`).

.. The client `SHOULD` include a
Content-Disposition header field <<RFC6266>>
with a "type" parameter set to "attachment", and a
"filename" parameter that indicates the name of the
attachment.  Note that the use of Content-Disposition as a
request header field is nonstandard and specific to this
protocol.

.. The client `MAY` include a Prefer
header field <<RFC7240>> with the "`return=representation`"
preference to request that the modified calendar object
resource be returned as the body of a successful response
to the `POST` request.

. When the server receives the `POST` request it does the following:

.. Validates that any recurrence instances referred to via
the "`rid`" query parameter are valid for the calendar
object resource being targeted.

.. Stores the supplied attachment data into a resource and
generates an appropriate URI for clients to access the
resource.

.. For each affected recurrence instance in the calendar
object resource targeted by the request, the server adds
an "`ATTACH`" property, whose value is the URI of the stored
attachment.
The "`ATTACH`" property `MUST` contain a "`MANAGED-ID`"
parameter whose value is a unique identifier (within the
context of the server as a whole).
The "`ATTACH`" property `SHOULD` contain an "`FMTTYPE`"
parameter whose value matches the Content-Type header
field value from the request.
The "`ATTACH`" property `SHOULD` contain an "`FILENAME`"
parameter whose value matches the Content-Disposition
header field "filename" parameter value from the request, taking
into account the restrictions expressed in
<<FILENAME-parameter>>.
The "`ATTACH`" property `SHOULD` include a "`SIZE`" parameter
whose value represents the size in octets of the
attachment.
If a specified recurrence instance does not have a
matching component in the calendar object resource, then
the server `MUST` modify the calendar object resource to
include an overridden component with the appropriate
"`RECURRENCE-ID`" property.

.. Upon successful creation of the attachment resource,
and modification of the targeted calendar object resource,
the server `MUST` return an appropriate HTTP success status
response and include a "Cal-Managed-ID" header field
containing the "`MANAGED-ID`" parameter value of the newly
created "`ATTACH`" property. The client can use the
"`Cal-Managed-ID`" header field value to correlate the attachment
with "`ATTACH`" properties added to the calendar object
resource.
If the client included a Prefer header field with the
"return=representation" preference in the request, the
server `SHOULD` return the modified calendar object
resource as the body of the response.  Otherwise, the
server can expect that the client will reload the
calendar object resource with a subsequent GET request to
refresh any local cache.

In the following example, the client adds a new attachment to
a non recurring event and asks the server (via the
Prefer <<RFC7240>> header field) to return the
modified version of that event in the response.

[source%unnumbered]
----
>> Request <<

POST /events/64.ics?action=attachment-add HTTP/1.1
Host: cal.example.com
Content-Type: text/html; charset="utf-8"
Content-Disposition:attachment;filename=agenda.html
Content-Length: xxxx
Prefer: return=representation

<html>
  <body>
<h1>Agenda</h1>
  </body>
</html>

>> Response <<

HTTP/1.1 201 Created
Content-Type: text/calendar; charset="utf-8"
Content-Length: yyyy
Content-Location: https://cal.example.com/events/64.ics
ETag: "123456789-000-111"
Cal-Managed-ID: 97S

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Server//EN
BEGIN:VEVENT
UID:20010712T182145Z-123401@example.com
DTSTAMP:20120201T203412Z
DTSTART:20120714T170000Z
DTEND:20120715T040000Z
SUMMARY:One-off meeting
ATTACH;MANAGED-ID=97S;FMTTYPE=text/html;SIZE=xxxx;
 FILENAME=agenda.html:https://cal.example.com/attach/64/34X22R
END:VEVENT
END:VCALENDAR
----

[[attachment-update]]
=== Adding attachments

When an attachment is updated the server `MUST` change the
associated "`MANAGED-ID`" parameter and `MAY` change the "`ATTACH`"
property value. With this approach, clients are able to
determine when an attachment has been updated by some other
client by looking for a change to either the "`ATTACH`" property
value, or the "`MANAGED-ID`" parameter value.

To change the data of an existing managed attachment in a
calendar object resource, the following occurs:

. The client issues a `POST` request targeted at the calendar object resource.

.. The request-URI will include an "`action`" query
parameter with the value "attachment-update" (see
<<action>>).

.. The request-URI will include a "`managed-id`" query
parameter with the value matching that of the "`MANAGED-ID`"
parameter for the "`ATTACH`" property being updated (see
<<managed-id>>).

.. The body of the request contains the updated data for
the attachment.

.. The client `MUST` include a valid Content-Type header field
describing the media type of the attachment (as required
by HTTP).

.. The client `SHOULD` include a
Content-Disposition header field <<RFC6266>> with a
"`type`" parameter set to "`attachment`", and a "`filename`"
parameter that indicates the name of the attachment.

.. The client `MAY` include a Prefer
header field <<RFC7240>> with the "`return=representation`"
preference to request that the modified calendar object
resource be returned as the body of a successful response
to the `POST` request.

. When the server receives the `POST` request it does the following:

.. Validates that the "`managed-id`" query parameter is
valid for the calendar object resource.

.. Updates the content of the attachment resource
corresponding to that managed-id with the supplied
attachment data.

.. For each affected recurrence instance in the calendar
object resource targeted by the request, the server
updates the "`ATTACH`" property whose "`MANAGED-ID`" property
parameter value matches the "`managed-id`" query
parameter. The "`MANAGED-ID`" parameter value is changed to
allow other clients to detect the update, and the property
value (attachment URI) might also be changed. The "`ATTACH`"
property `SHOULD` contain a "`FMTTYPE`" parameter whose value
matches the Content-Type header field value from the request -
this could differ from the original value if the media
type of the updated attachment is different. The "`ATTACH`"
property `SHOULD` contain a "`FILENAME`" parameter whose value
matches the Content-Disposition header field "`filename`"
parameter value from the request, taking into account the
restrictions expressed in
"`FILENAME-parameter`". The "`ATTACH`" property
`SHOULD` include a "`SIZE`" parameter whose value represents
the size in octets of the updated attachment.

.. Upon successful update of the attachment resource, and
modification of the targeted calendar object resource, the
server `MUST` return an appropriate HTTP success status
response, and include a "`Cal-Managed-ID`" header field
containing the new value of the "`MANAGED-ID`" parameter.
The client can use the
"`Cal-Managed-ID`" header field value to correlate the attachment
with "`ATTACH`" properties added to the calendar object
resource.
If the client included a Prefer header field with the
"`return=representation`" preference in the request, the
server `SHOULD` return the modified calendar object
resource as the body of the response. Otherwise, the
server can expect that the client will reload the
calendar object resource with a subsequent GET request to
refresh any local cache.

The update operation does not take a "`rid`" parameter and
does not add, or remove, any "`ATTACH`" property in the
targeted calendar object resource. To link an existing
attachment to a new instance, the client simply does a `PUT` on
the calendar object resource, adding an "`ATTACH`" property
which duplicates the existing one (see
<<attachment-add-put>>).

In the following example, the client updates an existing
attachment and asks the server (via the
Prefer <<RFC7240>> header field) to return the
updated version of that event in the response.

[source%unnumbered]
----
>> Request <<

POST /events/64.ics?action=attachment-update&managed-id=97S HTTP/1.1
Host: cal.example.com
Content-Type: text/html; charset="utf-8"
Content-Disposition:attachment;filename=agenda.html
Content-Length: xxxx
Prefer: return=representation

<html>
  <body>
    <h1>Agenda</h1>
    <p>Discuss attachment draft</p>
  </body>
</html>

>> Response <<

HTTP/1.1 200 OK
Content-Type: text/calendar; charset="utf-8"
Content-Length: yyyz
Content-Location: https://cal.example.com/events/64.ics
Cal-Managed-ID: 98S
ETag: "123456789-000-222"

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Server//EN
BEGIN:VEVENT
UID:20010712T182145Z-123401@example.com
DTSTAMP:20120201T203412Z
DTSTART:20120714T170000Z
DTEND:20120715T040000Z
SUMMARY:One-off meeting
ATTACH;MANAGED-ID=98S;FMTTYPE=text/html;SIZE=xxxy;
 FILENAME=agenda.html:https://cal.example.com/attach/64/34X22R
END:VEVENT
END:VCALENDAR
----

[[attachment-remove]]
=== Removing Attachments via `POST`

To remove an existing attachment from a calendar object,
the following occurs:

. The client issues a POST request targeted at the calendar
object resource.

.. The request-URI will include an "`action`" query
parameter with the value "`attachment-remove`" (see
<<action>>).

.. If all recurrence instances are having an attachment
removed, the "`rid`" query parameter is not present in the
`request-URI`. If one or more specific recurrence instances
are targeted, then the `request-URI` will include a "`rid`"
query parameter containing the list of instances (see
<<rid>>).

.. The request-URI will include a "`managed-id`" query
parameter with the value matching that of the "`MANAGED-ID`"
property parameter for the "`ATTACH`" property being removed
(see <<managed-id>>).

.. The body of the request will be empty.

.. The client `MAY` include a Prefer
header field <<RFC7240>> with the "`return=representation`"
preference to request that the modified calendar object
resource be returned as the body of a successful response
to the `POST` request.

. When the server receives the `POST` request it does the following:

.. Validates that any recurrence instances referred to via
the "`rid`" query parameter are valid for the calendar
object resource being targeted.

.. Validates that the "`managed-id`" query parameter is
valid for the calendar object resource and specific
instances being targeted.

.. For each affected recurrence instance in the calendar
object resource targeted by the request, the server
removes the matching "`ATTACH`" property. Note that if a
specified recurrence instance does not have a matching
component in the calendar object resource, then the server
`MUST` modify the calendar object resource to include an
overridden component with the appropriate "`RECURRENCE-ID`"
property, and the matching "`ATTACH`" property
removed. This later case is actually valid only if the
master component does include the referenced "`ATTACH`"
property.

.. If the attachment resource is no longer referenced by
any instance of the calendar object resource, the server
can delete the attachment resource to free up storage
space.

.. Upon successful removal of the attachment resource and
modification of the targeted calendar object resource, the
server `MUST` return an appropriate HTTP success status
response.
If the client included a Prefer header field with the
"`return=representation`" preference in the request, the
server `SHOULD` return the modified calendar object
resource as the body of the response. Otherwise, the
server can expect that the client will reload the
calendar object resource with a subsequent `GET` request to
refresh any local cache.

In the following example, the client deletes an existing
attachment by passing its managed-id in the request.
The Prefer <<RFC7240>> header field is not
set in the request so the calendar object resource data is
not returned in the response.

[source%unnumbered]
----
>> Request <<

POST /events/64.ics?action=attachment-remove&managed-id=98S HTTP/1.1
Host: cal.example.com
Content-Length: 0

>> Response <<

HTTP/1.1 204 No Content
Content-Length: 0
----

[[attachment-add-put]]
=== Adding Existing Managed Attachments via `PUT`

Clients can make use of existing managed attachments by
adding the corresponding "`ATTACH`" property to calendar object
resources (subject to the restrictions described in
<<acls>>).

If a managed attachment is used in more than calendar resource,
servers `SHOULD NOT` change
either the "`MANAGED-ID`" parameter value or the "`ATTACH`"
property value for these attachments - this ensures that
clients do not have to download the attachment data again if
they already have it cached.
Additionally, servers `SHOULD` validate
"`SIZE`" parameter values and replace incorrect values with the
actual sizes of existing attachments.

These `PUT` requests are subject to the preconditions listed in
<<errors>>.

[[attachment-update-put]]
=== Updating Attachments via `PUT`

Servers `MUST NOT` allow clients to update attachment data
directly via a `PUT` on the attachment URI (or via any other
HTTP method that modifies content). Instead, attachments can
only be updated via use of POST requests on the calendar
data.

[[attachment-remove-put]]
=== Removing Attachments via `PUT`

Clients can remove attachments by simply re-writing the
calendar object resource data to remove the appropriate
"`ATTACH`" properties. Servers `MUST NOT` allow clients to delete
attachments directly via a `DELETE` request on the attachment
URI.

[[attachment-retrieve]]
=== Retrieving Attachments

Clients retrieve attachments by issuing an HTTP `GET` request
using the value of the corresponding "`ATTACH`" property as the
request-URI, taking into account the substitution mechanism
associated with the "`CALDAV:managed-attachments-server-URL`"
property (see <<attach-server-URL-property>>).

[[errors]]
=== Error Handling

This specification creates additional preconditions for
the `POST` method.

The new preconditions are:

(`CALDAV:max-attachment-size`):: The attachment submitted
in the POST request MUST have an octet size less than or
equal to the value of the `CALDAV:max-attachment-size`
property value (<<max-attachment-size-property>>) on the calendar
collection of the target calendar resource;

(`CALDAV:max-attachments-per-resource`):: The addition of
the attachment submitted in the `POST` request `MUST` result
in the target calendar resource having a number of managed
attachments less than or equal to the value of the
`CALDAV:max-attachments-per-resource` property value
(<<max-attachments-per-resource-property>>) on the
calendar collection of the target calendar resource;

(`CALDAV:valid-action`):: The `action` query
parameter in the `POST` request
`MUST` contain one of "`attachment-add`", "`attachment-update`",
or "`attachment-remove`".

(`CALDAV:valid-rid`):: The `rid` query
parameter in the `POST` request
`MUST NOT` be present for an attachment-update action, and
`MUST` contain the value "`M`" and/or values corresponding to
"`RECURRENCE-ID`" property values in the iCalendar
data targeted by the request.

(`CALDAV:valid-managed-id`):: The `managed-id` query
parameter in the `POST` request
`MUST NOT` be present for an `attachment-add` action, and
`MUST` contain a value corresponding to a
"`MANAGED-ID`" property parameter value in the iCalendar
data targeted by the request.

A `POST` request to add, modify, or delete a managed
attachment results in an implicit modification of the
targeted calendar resource (equivalent of a `PUT`). As a
consequence, clients should also be prepared to handle
preconditions associated with this implicit `PUT`. This
includes (but is not limited to):

* (`CALDAV:max-resource-size`) (from
<<RFC4791,section=5.3.2.1>>)

* (`DAV:quota-not-exceeded`) (from
<<RFC4331,section=6>>)</t>

* (`DAV:sufficient-disk-space`) (from
<<RFC4331,section=6>>)

A `PUT` request to add or modify and existing calendar
object resource can make reference to an existing managed
attachment. The following new preconditions is defined:

(`CALDAV:valid-managed-id-parameter`):: a "`MANAGED-ID`"
property parameter value in the iCalendar data in the `PUT`
request is not valid (e.g., does not match any existing
managed attachment).

If a precondition for a request is not satisfied:

. The response status of the request `MUST` either be
403 (Forbidden), if the request should not be repeated because
it will always fail, or 409 (Conflict), if it is expected that
the user might be able to resolve the conflict and resubmit
the request.

. The appropriate XML element `MUST` be returned as the
child of a top-level `DAV:error` element in the response
body.

=== Additional Considerations

[[quotas]]
==== Quotas

The WebDAV Quotas <<RFC4331>>
specification defines two live WebDAV properties
(DAV:quota-available-bytes and `DAV:quota-used-bytes`) to
communicate storage quota information to clients.
Server implementations `MAY` choose to include managed
attachments sizes when calculating the amount of storage
used by a particular resource.

[[acls]]
==== Access Control

Access to the managed attachments store in a calendar
object resource `SHOULD` be restricted to only those calendar
users who have access to that calendar object either directly,
or indirectly (via being an attendee who would receive a
scheduling message).

When accessing a managed attachment, clients `SHOULD` be
prepared to authenticate with the server storing the
attachment resource. The credentials required to access the
managed attachment store could be different from the ones used
to access the CalDAV server.

This specification only allows organizers of scheduled
events to add managed attachments. Servers `MUST` prevent
attendees of scheduled events from adding, updating or
removing managed attachments. In addition, the server `MUST`
prevent a calendar user from re-using a managed attachment
(based on its managed-id value), unless that user is the one
who originally created the managed attachment.

[[redirects]]
==== Redirects

For `POST` requests that add or update attachment data, the
server `MAY` issue
a 307 (Temporary Redirect) <<RFC7231>>
or 308 (Permanent Redirect) <<RFC7538>>
response to require the client to
re-issue the `POST` request using a different `request-URI`. As
a result, clients `SHOULD` use the
"`100-continue`" expectation defined in
<<RFC7231,section=5.1.1>>.
Using this mechanism ensures that, if a redirect does occur,
the client does not needlessly send the attachment data.

[[processing]]
==== Processing Time

Clients can expect servers to take a while to respond to
`POST` requests that include large attachment bodies. Servers
`SHOULD` use the "`102 (Processing)`" interim response defined
in <<RFC2518,section=10.1>> to keep the client
connection alive if the `POST` request will take significant
time to complete.

[[auto-cleanup]]
==== Automatic Clean-Up by Servers

Servers `MAY` automatically remove attachment data, for
example to regain the storage taken by unused attachments,
or as the result of a virus scanning. When doing so they
`SHOULD NOT` modify calendar data referencing those
attachments. Instead they `SHOULD` respond with "`410 (Gone)`"
to any request on the removed attachment URI.

==== Sending Scheduling Messages with Attachments

When a managed attachment is added, updated or removed
from a calendar object resource, the server `MUST` ensure that
a scheduling message is sent to update any attendees with
the changes, as per <<RFC6638>>.

==== Migrating Calendar Data

When exporting calendar data from a CalDAV server
supporting managed attachments, clients `SHOULD` remove all
"`MANAGED-ID`" property parameters from "`ATTACH`" properties in
the calendar data. Similarly when importing calendar data
from another source, clients `SHOULD` remove any "`MANAGED-ID`"
property parameters on "`ATTACH`" properties (failure to do so
will likely result in the server removing those properties
automatically).
