== Modifications to iCalendar Syntax

[[SIZE-parameter]]
=== `SIZE` Property Parameter

Parameter Name:: `SIZE`

Purpose:: To specify the size of an attachment.

Format Definition:: This property parameter is defined by the following notation:
+
--
[source%unnumbered]
----
sizeparam = "SIZE" "=" paramtext
; positive integers
----
--

Description:: This property parameter `MAY` be specified on "`ATTACH`"
properties. It indicates the size in octets of the
corresponding attachment data. Since iCalendar integer
values are restricted to a maximum value of
2147483647, the current parameter is defined as text
to allow an extended range to be used.

Example::
+
--
[source%unnumbered]
----
ATTACH;SIZE=1234:https://attachments.example.com/abcd.txt
----
--

[[FILENAME-parameter]]
=== `FILENAME` Property Parameter

Parameter Name:: `FILENAME`

Purpose:: To specify the file name of a managed attachment.

Format Definition:: This property parameter is defined by the following notation:
+
--
[source%unnumbered]
----
filenameparam = "FILENAME" "=" paramtext
----
--

Description:: This property parameter `MAY` be specified on "`ATTACH`"
properties corresponding to managed attachments.
Its value provides information on how to construct a
filename for storing the attachment data.
This parameter is very similar in nature to the
Content-Disposition HTTP header field "filename" parameter
and exposes the same security risks.
As a consequence, clients `MUST` follow the guidelines
expressed in <<RFC6266,section=4.3>>
when consuming this parameter value.
Similarly, servers `MUST` follow those same guidelines
before storing a value.

Example::
+
--
[source%unnumbered]
----
ATTACH;FILENAME=agenda.html:https://attachments.example.com/rt452S
----
--

[[MANAGED-ID-parameter]]
=== `MANAGED-ID` Property Parameter

Parameter Name:: `MANAGED-ID`

Purpose:: To uniquely identify a managed attachment.

Format Definition:: This property parameter is defined by the following notation:
+
--
[source%unnumbered]
----
managedidparam = "MANAGED-ID" "=" paramtext
----
--

Description:: This property parameter `MUST` be specified on "`ATTACH`"
properties corresponding to managed attachments.
Its value is generated by the server and uniquely
identifies a managed attachment within the scope of
the CalDAV server.
This property parameter `MUST NOT` be present in the
case of non-managed attachments.

Example::
+
--
[source%unnumbered]
----
ATTACH;MANAGED-ID=aUNhbGVuZGFy:https://attachments.example.com/abcd.txt
----
--
